# This is a basic workflow that is manually triggered

name: SWG Deployment Workflow
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - 'deploy/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: jungwinter/split@master
      id: branch
      with:
        msg: ${{ github.ref_name }}
        separator: "/"
    # Runs a single command using the runners shell
    - name: Send greeting
      run:
      - echo "Hello ${{ steps.branch.outputs._2 }}"
