on:
  push:
    branches:
    - 'deploy/npe/**'

jobs:
  deployment:
    run-name: Deploy to ${{ github.ref }} by @${{ github.actor }}
    runs-on: self-hosted
    environment: non-production
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: jungwinter/split@master
      id: branch
      with:
        msg: ${{ github.ref_name }}
        separator: "/"
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Triggger deployment
      env:
        JEKINES_SECRET: ${{ secrets.JENKINS }}
      run: |
        echo "Environment: ${{ steps.branch.outputs._1 }}"
        echo "Pop: ${{ steps.branch.outputs._2 }}"
        echo "Version: ${{ steps.branch.outputs._3 }}"
        bash ./scripts/triggerDeployment.sh ${{ steps.branch.outputs._1 }} ${{ steps.branch.outputs._2 }} ${{ steps.branch.outputs._3 }} $JEKINES_SECRET
