# This is a basic workflow that is manually triggered

name: SWG Deployment Workflow for non-production environment
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - 'deploy/npe/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deployment:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: jungwinter/split@master
      id: branch
      with:
        msg: ${{ github.ref_name }}
        separator: "/"
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Triggger deployment
      env:
        JEKINES_SECRET: ${{ secrets.JENKINS }}
      run: |
        echo "Environment: ${{ steps.branch.outputs._1 }}"
        echo "Pop: ${{ steps.branch.outputs._2 }}"
        echo "Version: ${{ steps.branch.outputs._3 }}"
        bash ./scripts/triggerDeployment.sh ${{ steps.branch.outputs._1 }} ${{ steps.branch.outputs._2 }} ${{ steps.branch.outputs._3 }} $JEKINES_SECRET
